confignext/confignext/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses_tracker_app.urls')),
]

confignext/expenses_tracker_app/urls.py
from django.urls import path

confignext/expenses_tracker_app/models.py
from django.db import models


# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    budget = models.IntegerField(default=None)

    class Meta:
        verbose_name_plural = 'Profiles'


class Expenses(models.Model):
    title = models.CharField(max_length=50)
    image_url = models.URLField(default=None)
    description = models.TextField(default=None)
    price = models.FloatField(default=None)

    class Meta:
        verbose_name_plural = 'Expenses'

confignext/templates/expense-create.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Create Expense</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw">
        <label for="name">Title</label>
        <input type="text" name="title" maxlength="50" required="" id="id_title">

        <label for="description">Description</label>
        <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>

        <label for="imageUrl">Link to Image</label>
        <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">

        <label for="price">Price</label>
        <input type="number" name="price" step="any" required="" id="id_price">

        <input type="submit" value="Create">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/expense-delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Delete Expense</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc"> 
        <label for="name">Title</label>
        <input type="text" name="title" value="Electrical Piano" maxlength="50" disabled="" required="" id="id_title">

        <label for="description">Description</label>
        <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>

        <label for="image_url">Link to Image</label>
        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" disabled="" required="" id="id_image_url">

        <label for="price">Price</label>
        <input type="number" name="price" value="1000.0" step="any" disabled="" required="" id="id_price">

        <input type="submit" value="Delete">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/expense-edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Edit Expense</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS">
        <label for="name">Title</label>
        <input type="text" name="title" value="Electrical Piano" maxlength="50" required="" id="id_title">

        <label for="description">Description</label>
        <textarea name="description" cols="40" rows="10" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>

        <label for="image_url">Link to Image</label>
        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" required="" id="id_image_url">

        <label for="price">Price</label>
        <input type="number" name="price" value="1000.0" step="any" required="" id="id_price">

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/home-no-profile.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your data</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0">
        <label for="budget">Budget</label>
        <input type="number" name="budget" required="" id="id_budget">

        <label for="firstName">First Name</label>
        <input type="text" name="first_name" maxlength="15" required="" id="id_first_name">

        <label for="lastName">Last Name</label>
        <input type="text" name="last_name" maxlength="15" required="" id="id_last_name">

        <input type="submit" value="Submit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/home-with-profile.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        

<div>
    <h1>Summary</h1><h1>
    <ul class="expenses-list">
    <li class="blue">1500$</li>
    
        <li class="red"> - 1000.0$</li>
    
        <li class="red"> - 400.0$</li>
    
    <li class="green">= 100.0$ left</li>
    </ul>
</h1></div>

<h1>My Expenses</h1>
<a href="/create">Add Expense</a>
<div class="expenses-container">
    
        <div class="expense-container">
    <h2>Electrical Piano</h2>
    <hr>
    <img src="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png">
    <p>I bought myself a new piano to improve my skills</p>
    <div class="expense-detail">
        <div>
            <p>Price: 1000.0$</p>
        </div>
        <div class="right">
            <a class="button edit" href="/edit/3">Edit</a>
            <a class="button delete" href="/delete/3">Delete</a>
        </div>
    </div>
</div>
    
        <div class="expense-container">
    <h2>TV</h2>
    <hr>
    <img src="https://lh3.googleusercontent.com/proxy/nCJ4jT2qWgkNO95Y3YSePfew9lqa0AkeQoLLi5LM_ZbT_S_KdizZdZq3YzUm32kGNBk3DyM4eKwEmk0VX9esNR1NV5Ji480jF9pte79893Ml8C-kdw">
    <p>My old tv broke, so I bought myself a new one.</p>
    <div class="expense-detail">
        <div>
            <p>Price: 400.0$</p>
        </div>
        <div class="right">
            <a class="button edit" href="/edit/4">Edit</a>
           <a class="button delete" href="/delete/4">Delete</a>
        </div>
    </div>
</div>
    
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/profile-delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Are you sure you want to delete your profile?</h1>
<form method="POST">
<input type="hidden" name="csrfmiddlewaretoken" value="fewGdgFCGlbXTIgYQJKFmURDSd5iqPnic2eEdlplu3qQSU6nCpeMdM4pau3rc0w3">
<button class="delete">Confirm</button>
</form>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/profile-edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your new data</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="M6BlBJtidtTAjIVkeKKrO0pzGsJVBeMuJUjjBOd11b8tiULJ0qeyFSClYJH4npVf">
        <label for="budget">Budget</label>
        <input type="number" name="budget" value="1500" required="" id="id_budget">

        <label for="firstName">First Name</label>
        <input type="text" name="first_name" value="Tanya" maxlength="15" required="" id="id_first_name">

        <label for="lastName">Last Name</label>
        <input type="text" name="last_name" value="Staneva" maxlength="15" required="" id="id_last_name">

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

confignext/templates/profile.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Your Profile</h1>
<div class="expenses-container">
    <div class="expense-container">
        <h2>Tanya Staneva</h2>
        <hr>
        <img src="./static/images/user.png">
        <p>In your profile you can edit your profile data</p>
        <div class="expense-detail">
            <div>
                <p>Budget Left: 100.0$</p>
            </div>
            <div class="right">
                <a class="button edit" href="/profile/edit">Edit Profile</a>
                <a class="button delete" href="/profile/delete">Delete Profile</a>
            </div>
        </div>
    </div>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>